version: "2"

services:
  mysql:
    build:
      context: .
    environment:
      MYSQL_DATABASE: 'chat'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql